### ISSUE TITLE
Crash with Excompressum

### ISSUE THREAD

**Issue by nanmumc** [embeddedt/ArchaicFix#118]
I upgraded the GTNH from 2.5.1 to 2.6.0, then the game will be crashed if I look at an autoSieve (self-added, but work well in GTNH 2.5.1). Finally, I found that this problem can be solved by deleting this mod “archaicfix-0.7.2.jar”. However, I am not sure whether it caused this problem. Here is the crash report:

`---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-04-29 16:37:25 CST
Description: Rendering Block Entity

java.lang.NoClassDefFoundError: net/minecraft/client/resources/SkinManager$2
    at net.minecraft.client.resources.SkinManager.func_152789_a(SkinManager.java:90)
    at net.minecraft.client.resources.SkinManager.func_152792_a(SkinManager.java:67)
    at net.blay09.mods.excompressum.client.render.tile.RenderAutoSieve.bindPlayerTexture(RenderAutoSieve.java:110)
    at net.blay09.mods.excompressum.client.render.tile.RenderAutoSieve.renderTileEntityAt(RenderAutoSieve.java:79)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntityAt(SourceFile:100)
    at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:43)
    at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.renderTileEntity(SourceFile:92)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTE(SodiumWorldRenderer.java:332)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:345)
    at net.minecraft.client.renderer.RenderGlobal.handler$zja000$angelica$sodium$renderTileEntities(RenderGlobal.java:6253)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:476)
    at net.minecraft.client.renderer.EntityRenderer.redirect$zcf000$hydroenergy$redirectRenderEntities(EntityRenderer.java:6579)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1224)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.run(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Block Entity Details --
Details:
    Name: autoSieve // net.blay09.mods.excompressum.tile.TileEntityAutoSieveRF
    Block type: ID #189 (tile.excompressum:auto_sieve // net.blay09.mods.excompressum.block.BlockAutoSieveRF)
    Block data value: 3 / 0x3 / 0b0011
    Block location: World: (214,120,392), Chunk: (at 6,7,8 in 13,24; contains blocks 208,0,384 to 223,255,399), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #189 (tile.excompressum:auto_sieve // net.blay09.mods.excompressum.block.BlockAutoSieveRF)
    Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:103)
    at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:43)
    at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTE(SodiumWorldRenderer.java:332)
    at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:345)
    at net.minecraft.client.renderer.RenderGlobal.handler$zja000$angelica$sodium$renderTileEntities(RenderGlobal.java:6253)
    at net.minecraft.client.renderer.RenderGlobal.func_147589_a(RenderGlobal.java:476)
    at net.minecraft.client.renderer.EntityRenderer.redirect$zcf000$hydroenergy$redirectRenderEntities(EntityRenderer.java:6579)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1224)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:71)
    at oolloo.jlw.Wrapper.main(Wrapper.java:51)
`

**Comment by embeddedt** [comment]
Please send the full `fml-client-latest.log` file.

**Comment by nanmumc** [comment]
[fml-client-latest.log](https://github.com/embeddedt/ArchaicFix/files/15150930/fml-client-latest.log)
Ok, please see attached

**Comment by embeddedt** [comment]
The crash appears to be a conflict with CustomSkinLoader. Where can I find the version of this mod for 1.7.10?

**Comment by nanmumc** [comment]
From here: https://www.mcmod.cn/download/883.html
Select [1.7.10] and click here:
![image](https://github.com/embeddedt/ArchaicFix/assets/25528572/0587de4a-6c94-40f5-afba-0b70f2d16bbd)
input a captcha and then click here to download:
![image](https://github.com/embeddedt/ArchaicFix/assets/25528572/4cf9fb31-f3d5-4d33-ba8e-316b3432ca0c)
